from . import res_company
from . import res_partner
from . import account_move
from . import hs_code
from . import intrastat_product_declaration
from . import intrastat_region
from . import intrastat_transaction
from . import intrastat_transport_mode
from . import intrastat_unit
from . import sale_order
from . import stock_warehouse
