[project]
name = "odoo-addons-oca-intrastat-extrastat"
version = "18.0.20250515.0"
dependencies = [
    "odoo-addon-intrastat_base==18.0.*",
    "odoo-addon-intrastat_product==18.0.*",
    "odoo-addon-product_harmonized_system==18.0.*",
    "odoo-addon-product_harmonized_system_delivery==18.0.*",
    "odoo-addon-product_harmonized_system_stock==18.0.*",
    "odoo-addon-product_harmonized_system_tax_rate==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
